name: CD Pipeline

on:
  push:
    branches: [develop] # Tự động chạy khi code được merge vào develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Quan trọng: Cấp quyền ghi vào Packages cho GITHUB_TOKEN

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          # Bước then chốt: Chuyển tên Repo về chữ thường
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo "Building image: $IMAGE_ID:${{ github.sha }}"

          # Build image với tag là mã SHA của commit để phục vụ rollback
          docker build -t $IMAGE_ID:${{ github.sha }} .
          
          # Push image lên kho lưu trữ
          docker push $IMAGE_ID:${{ github.sha }}
  deploy-and-test:
    needs: build-and-push # Đợi Build xong mới Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Kết nối SSH và Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASSWORD }} # Đổi từ key sang password
          script: |
            # 1. Kiểm tra nếu chưa có code thì clone về (Đổi link clone thành link của repo nhóm ông nhé)
            if [ ! -d "CI_CD_Pipeline_NT208.Q23" ]; then
              git clone https://github.com/NT208-Q23-Nhom-11/CI_CD_Pipeline_NT208.Q23.git
            fi
            
            # 2. Di chuyển vào thư mục code trên Server
            cd CI_CD_Pipeline_NT208.Q23
            
            # 3. Cập nhật code script mới nhất
            git pull origin develop
            
            # 4. Cấp quyền và chạy file deploy
            chmod +x scripts/deploy.sh
            bash scripts/deploy.sh ${{ github.sha }}

      - name: Smoke Test #(Kiểm tra app)
        id: smoke_test
        run: |
          echo "Đợi 10s cho ứng dụng khởi động..."
          sleep 10
          curl -v http://${{ secrets.STAGING_HOST }}:5000/health | grep "ok"
          # Gọi thử vào API health đã viết
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://${{ secrets.STAGING_HOST }}:5000/health)
          
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Smoke test THẤT BẠI. Ứng dụng trả về mã: $HTTP_STATUS"
            exit 1
          fi
          echo "Smoke test THÀNH CÔNG!"

      - name: Rollback Tự Động (Chỉ chạy nếu Smoke Test bị lỗi)
        if: failure() # Lệnh bắt lỗi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASSWORD }} # Đổi từ key sang password
          script: |
            cd CI_CD_Pipeline_NT208.Q23
            bash scripts/rollback.sh