name: CD Pipeline

on:
  push:
    branches: [develop] # Tự chạy khi merge vào develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push
        run: |
          # Chuyển tên repo về chữ thường cho đúng chuẩn Docker
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Tag bằng mã SHA để rollback chính xác [cite: 63, 76]
          docker build -t $IMAGE_ID:${{ github.sha }} .
          docker push $IMAGE_ID:${{ github.sha }}